name: Update Gradle Wrapper


on:
  workflow_dispatch:

  schedule:
    - cron: "0 5 * * 1"


jobs:
  update-gradle-wrapper:

    runs-on: ubuntu-24.04

    steps:
      # https://github.com/actions/checkout
      - name: Checkout Git repository
        uses: actions/checkout@v6.0.2

      # https://github.com/gradle/wrapper-validation-action
      - name: Wrapper validation
        uses: gradle/actions/wrapper-validation@v5.0.0

      - name: Make Gradlew executable
        run: chmod +x ./gradlew

      # https://github.com/gradle-update/update-gradle-wrapper-action
      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@v2.1.0
        with:
          release-channel: stable
          labels: dependencies